/*
 * This file is generated by jOOQ.
 */
package mixailche.jsonplaceholder.proxy.jooq.enums;


import mixailche.jsonplaceholder.proxy.jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum EventMethod implements EnumType {

    GET("GET"),

    POST("POST"),

    PUT("PUT"),

    DELETE("DELETE");

    private final String literal;

    private EventMethod(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "event_method";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static EventMethod lookupLiteral(String literal) {
        return EnumType.lookupLiteral(EventMethod.class, literal);
    }
}
