/*
 * This file is generated by jOOQ.
 */
package mixailche.jsonplaceholder.proxy.jooq;


import java.util.Arrays;
import java.util.List;

import mixailche.jsonplaceholder.proxy.jooq.tables.Databasechangelog;
import mixailche.jsonplaceholder.proxy.jooq.tables.Databasechangeloglock;
import mixailche.jsonplaceholder.proxy.jooq.tables.Events;
import mixailche.jsonplaceholder.proxy.jooq.tables.Roles;
import mixailche.jsonplaceholder.proxy.jooq.tables.UserRoles;
import mixailche.jsonplaceholder.proxy.jooq.tables.Users;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.events</code>.
     */
    public final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>public.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.user_roles</code>.
     */
    public final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Events.EVENTS,
            Roles.ROLES,
            UserRoles.USER_ROLES,
            Users.USERS
        );
    }
}
