/*
 * This file is generated by jOOQ.
 */
package com.jsonplaceholder.proxy.jooq;


import com.jsonplaceholder.proxy.jooq.tables.Databasechangelog;
import com.jsonplaceholder.proxy.jooq.tables.Databasechangeloglock;
import com.jsonplaceholder.proxy.jooq.tables.Events;
import com.jsonplaceholder.proxy.jooq.tables.Roles;
import com.jsonplaceholder.proxy.jooq.tables.UserRoles;
import com.jsonplaceholder.proxy.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.events</code>.
     */
    public static final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
